name: Build and Deploy Docs

on:
  push:
    branches:
      - doc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 默认为上面的branch

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload dist
        uses: actions/upload-artifact@v2 # 上传工件，方便后面共享
        with:
          name: docs
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          red: master   # 切换到master分支

      - name: Clear master
        run: |
          git fetch
          git config --global user.name "adoctors"
          git config --global user.email "qkeliang@163.com"
          git rm -rf .

      - name: Download dist     # 清空master分支后将dist文件下载到master
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: dist

      - name: Move dist to root and commit
        run: |
          mv dist/* .
          rm -rf dist
          git add .
          git commit -m "Update docs"
          echo "commit success!"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
