name: Build and Deploy Docs

on:
  push:
    branches:
      - doc

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: actions/upload-artifact@v2
        with:
          name: docs
          path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: docs
          path: dist

      - name: Commit and push changes
        run: |
          git config --global user.name "adoctors"
          git config --global user.email "qkeliang@163.com"
          git add .
          git commit -m "Update docs"
          git push origin master
